import { beforeEach, describe, expect, it } from 'vitest'
import { usePresenceStore } from '../domain/store'

const mobile=(componentId:string,patch:Record<string,unknown>)=>usePresenceStore.getState().mutate({actorId:'human',actorType:'human',label:'human edit',change:{componentId,breakpoint:'mobile',patch}} as never)
const request=()=>usePresenceStore.getState().requestAdmission({agentIdentity:{id:'browser-agent',displayName:'Your agent'},roleId:'responsive-collaborator',requestedScopes:[{resource:'breakpoint',id:'tablet',mode:'propose'}],reason:'I can handle Tablet while you finish Mobile.'})
const admit=()=>{const r=request();if(!r.ok)throw new Error('request failed');const id=r.data!.admissionId;const approved=usePresenceStore.getState().approveAdmission(id);if(!approved.ok)throw new Error('approve failed');return id}
const agent=(componentId:string,patch:Record<string,unknown>,expectedRevision:number,admissionId?:string)=>usePresenceStore.getState().mutate({actorId:'agent',actorType:'agent',admissionId,label:'agent edit',change:{componentId,breakpoint:'tablet',patch},expectedRevision,provisional:true} as never)

describe('Presence admission domain',()=>{
 beforeEach(()=>{localStorage.clear();usePresenceStore.getState().resetDemo()})
 it('starts with Tablet unassigned and no agent participant',()=>{const s=usePresenceStore.getState();expect(s.assignments.some(a=>a.breakpoint==='tablet')).toBe(false);expect(s.participants.some(p=>p.type==='agent')).toBe(false)})
 it('agent mutation before admission is rejected',()=>{const s=usePresenceStore.getState();const r=agent('hero',{gap:20},s.canonicalRevision);expect(r.ok).toBe(false);if(!r.ok)expect(r.error).toBe('ADMISSION_REQUIRED')})
 it('admission request creates pending state without mutation rights',()=>{const r=request();expect(r.ok).toBe(true);const s=usePresenceStore.getState();expect(s.admissions.at(-1)?.status).toBe('pending_user_approval');const m=agent('hero',{gap:20},s.canonicalRevision,s.admissions.at(-1)?.id);expect(m.ok).toBe(false);if(!m.ok)expect(m.error).toBe('ADMISSION_PENDING')})
 it('approval creates agent participant and Tablet proposal assignment',()=>{const id=admit();const s=usePresenceStore.getState();expect(s.admissions.find(a=>a.id===id)?.status).toBe('admitted');expect(s.participants.find(p=>p.id==='agent')?.name).toBe('Your agent');expect(s.assignments.some(a=>a.breakpoint==='tablet'&&a.participantId==='agent'&&a.mode==='propose')).toBe(true)})
 it('admitted agent can propose Tablet changes without canonical mutation',()=>{const id=admit();const s=usePresenceStore.getState();const r=agent('hero',{gap:20},s.canonicalRevision,id);expect(r.ok).toBe(true);expect(usePresenceStore.getState().canonicalRevision).toBe(1);expect(usePresenceStore.getState().proposals).toHaveLength(1)})
 it('admitted agent cannot mutate Mobile or Desktop',()=>{const id=admit();let s=usePresenceStore.getState();for(const breakpoint of ['mobile','desktop'] as const){const r=s.mutate({actorId:'agent',actorType:'agent',admissionId:id,label:'bad',change:{componentId:'hero',breakpoint,patch:{gap:10}},expectedRevision:s.canonicalRevision,provisional:true});expect(r.ok).toBe(false);if(!r.ok)expect(['CAPABILITY_NOT_GRANTED','SURFACE_NOT_ASSIGNED']).toContain(r.error)}})
 it('paused agent loses mutation rights and resume restores them',()=>{const id=admit();usePresenceStore.getState().pauseAdmission(id);let s=usePresenceStore.getState();let r=agent('hero',{gap:20},s.canonicalRevision,id);expect(r.ok).toBe(false);if(!r.ok)expect(r.error).toBe('ADMISSION_PAUSED');usePresenceStore.getState().resumeAdmission(id);s=usePresenceStore.getState();r=agent('hero',{gap:20},s.canonicalRevision,id);expect(r.ok).toBe(true)})
 it('revocation releases assignment and future mutation is rejected',()=>{const id=admit();usePresenceStore.getState().revokeAdmission(id);const s=usePresenceStore.getState();expect(s.assignments.some(a=>a.participantId==='agent')).toBe(false);const r=agent('hero',{gap:20},s.canonicalRevision,id);expect(r.ok).toBe(false);if(!r.ok)expect(r.error).toBe('ADMISSION_REVOKED')})
 it('revocation preserves an existing proposal for review',()=>{const id=admit();const s=usePresenceStore.getState();agent('hero',{gap:20},s.canonicalRevision,id);const proposalId=usePresenceStore.getState().proposals[0].id;usePresenceStore.getState().revokeAdmission(id);expect(usePresenceStore.getState().proposals.find(p=>p.id===proposalId)).toBeTruthy()})
 it('stale agent operation fails without mutating canonical state',()=>{const id=admit();const rev=usePresenceStore.getState().canonicalRevision;mobile('hero',{padding:30});const r=agent('hero',{gap:17},rev,id);expect(r.ok).toBe(false);if(!r.ok)expect(r.error).toBe('STALE_STATE');expect(usePresenceStore.getState().project.nodes.hero.responsive.tablet?.gap).toBe(28)})
 it('agent can recover after stale state by re-reading revision',()=>{const id=admit();const old=usePresenceStore.getState().canonicalRevision;mobile('hero',{padding:29});expect(agent('hero',{gap:16},old,id).ok).toBe(false);const fresh=usePresenceStore.getState().canonicalRevision;expect(agent('hero',{gap:16},fresh,id).ok).toBe(true)})
 it('proposal acceptance is canonical but rejection is not',()=>{const id=admit();let s=usePresenceStore.getState();agent('hero',{gap:19},s.canonicalRevision,id);s=usePresenceStore.getState();s.acceptProposal(s.proposals[0].id);expect(usePresenceStore.getState().project.nodes.hero.responsive.tablet?.gap).toBe(19);const rev=usePresenceStore.getState().canonicalRevision;agent('headline',{fontSize:45},rev,id);s=usePresenceStore.getState();const p=s.proposals.find(x=>x.status==='working')!;s.rejectProposal(p.id);expect(usePresenceStore.getState().project.nodes.headline.responsive.tablet?.fontSize).toBe(38)})
 it('individual proposal changes can be rejected',()=>{const id=admit();const rev=usePresenceStore.getState().canonicalRevision;agent('hero',{gap:18},rev,id);agent('headline',{fontSize:44},rev,id);const p=usePresenceStore.getState().proposals[0];usePresenceStore.getState().rejectProposalOperation(p.id,0);expect(usePresenceStore.getState().proposals[0].operations).toHaveLength(1)})
 it('human mutation increments revision and undo restores state',()=>{const r=mobile('hero',{padding:31});expect(r.ok).toBe(true);expect(usePresenceStore.getState().canonicalRevision).toBe(2);usePresenceStore.getState().undo();expect(usePresenceStore.getState().project.nodes.hero.responsive.mobile?.padding).toBe(22)})
 it('desktop remains protected',()=>{const s=usePresenceStore.getState();const r=s.mutate({actorId:'human',actorType:'human',label:'desktop edit',change:{componentId:'hero',breakpoint:'desktop',patch:{gap:1}}});expect(r.ok).toBe(false)})
 it('reset restores clean admission state',()=>{admit();usePresenceStore.getState().resetDemo();const s=usePresenceStore.getState();expect(s.canonicalRevision).toBe(1);expect(s.admissions).toHaveLength(0);expect(s.assignments.some(a=>a.breakpoint==='tablet')).toBe(false)})
})
