import { getPresenceState, usePresenceStore } from '../domain/store'
import type { ActivityEvent, AgentAdmission, Breakpoint, CapabilityScope, ResponsiveProps } from '../domain/types'

type ToolDef={name:string;description:string;inputSchema:Record<string,unknown>;execute:(input:unknown)=>unknown|Promise<unknown>}
declare global { interface Document { modelContext?: { registerTool:(tool:ToolDef)=>void } } }

const bp={type:'string',enum:['desktop','tablet','mobile']}
const ok=(data:unknown)=>({content:[{type:'text',text:JSON.stringify(data)}]})
const recordAgentActivity=(message:string,kind:ActivityEvent['kind']='system')=>usePresenceStore.setState(state=>({activities:[...state.activities,{id:`evt-webmcp-${Date.now()}-${Math.random().toString(36).slice(2,6)}`,actorId:'agent',actorType:'agent',message,kind,timestamp:Date.now(),revision:state.canonicalRevision}]}))
const markDiscovered=()=>{
 const state=getPresenceState()
 if(state.admissions.some(a=>['discovered','pending_user_approval','admitted','paused'].includes(a.status)))return
 const admission:AgentAdmission={id:`discovery-${Date.now()}`,agentIdentity:{id:'browser-agent',displayName:'Your agent',provider:'browser'},status:'discovered',requestedScopes:[],grantedScopes:[],sessionId:'presence-session',createdAt:Date.now()}
 usePresenceStore.setState(s=>({admissions:[...s.admissions,admission]}))
 recordAgentActivity('Agent discovered Presence capabilities')
}
export const toolNames=['inspect_presence','inspect_available_roles','request_admission','inspect_admission','inspect_project','inspect_breakpoint','inspect_component','inspect_constraints','inspect_recent_changes','compare_breakpoints','propose_layout_change','propose_component_change','propose_responsive_rule','submit_proposal','explain_proposal','release_role'] as const

export function registerWebMcp(){
 const mc=document.modelContext
 const store=getPresenceState()
 if(!mc){store.setWebMcp('unavailable');return false}
 const register=(tool:ToolDef)=>mc.registerTool(tool)

 register({name:'inspect_presence',description:'Inspect the live Presence workspace, current revision, human presence, admission support, available roles, and current admission state. Use this before requesting to join.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{markDiscovered();const s=getPresenceState();const admission=s.admissions.at(-1);return ok({application:{id:'presence',name:'Presence'},session:{id:'presence-session',humanPresent:true},project:{id:s.project.id,name:s.project.name,revision:s.canonicalRevision},admissionSupported:true,admission:admission?{id:admission.id,status:admission.status,roleId:admission.requestedRoleId}:null,availableRoles:s.roles.map(r=>({id:r.id,name:r.name,description:r.description,defaultScopes:r.defaultScopes}))})}})
 register({name:'inspect_available_roles',description:'Inspect collaborator roles and their default capability scopes before asking the human for admission.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{recordAgentActivity('Agent inspected available collaborator roles');return ok(getPresenceState().roles)}})
 register({name:'request_admission',description:'Request human approval to enter the live Presence workspace with a narrow collaborator role. This creates pending state but grants no mutation rights.',inputSchema:{type:'object',properties:{roleId:{type:'string',enum:['responsive-collaborator']},requestedScopes:{type:'array',items:{type:'object',properties:{resource:{type:'string',enum:['breakpoint']},id:bp,mode:{type:'string',enum:['propose']}},required:['resource','id','mode'],additionalProperties:false},minItems:1,maxItems:1},reason:{type:'string',minLength:1,maxLength:240}},required:['roleId','requestedScopes','reason'],additionalProperties:false},execute:(input)=>{const{roleId,requestedScopes,reason}=input as{roleId:string;requestedScopes:CapabilityScope[];reason:string};const s=getPresenceState();return ok(s.requestAdmission({agentIdentity:{id:'browser-agent',displayName:'Your agent',provider:'browser'},roleId,requestedScopes,reason}))}})
 register({name:'inspect_admission',description:'Inspect the latest admission request, its status, requested role, requested scopes, granted scopes, and reason.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{recordAgentActivity('Agent inspected admission status');const a=getPresenceState().admissions.at(-1);return ok(a??{status:'none'})}})

 register({name:'inspect_project',description:'Inspect current project identity, canonical revision, shared goal, participants, assignments, and active proposals. Re-run this after STALE_STATE.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{recordAgentActivity('Agent re-inspected project');const s=getPresenceState();return ok({project:{id:s.project.id,name:s.project.name},revision:s.canonicalRevision,goal:s.sharedGoal,assignments:s.assignments,participants:s.participants,proposals:s.proposals.map(p=>({id:p.id,status:p.status,breakpoint:p.breakpoint,count:p.operations.length,baseRevision:p.baseRevision}))})}})
 register({name:'inspect_breakpoint',description:'Inspect semantic component layout values for one responsive breakpoint. Use this before proposing layout changes and after stale state.',inputSchema:{type:'object',properties:{breakpoint:bp},required:['breakpoint'],additionalProperties:false},execute:(input)=>{const{breakpoint}=input as{breakpoint:Breakpoint};recordAgentActivity(`Agent inspected ${breakpoint} breakpoint`);const s=getPresenceState();return ok({breakpoint,revision:s.canonicalRevision,nodes:Object.values(s.project.nodes).map(n=>({id:n.id,name:n.name,type:n.type,props:n.props,responsive:n.responsive[breakpoint]??{}}))})}})
 register({name:'inspect_component',description:'Inspect a semantic component and its responsive values across all breakpoints.',inputSchema:{type:'object',properties:{componentId:{type:'string'}},required:['componentId'],additionalProperties:false},execute:(input)=>{const{componentId}=input as{componentId:string};const s=getPresenceState();const n=s.project.nodes[componentId];if(n)recordAgentActivity(`Agent inspected ${n.name}`);return ok(n??{error:'NOT_FOUND'})}})
 register({name:'inspect_constraints',description:'Inspect deterministic product constraints that all human and admitted-agent operations must satisfy.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{recordAgentActivity('Agent inspected workspace constraints');return ok(getPresenceState().constraints.filter(c=>c.enabled))}})
 register({name:'inspect_recent_changes',description:'Inspect recent human, agent, and system activity with revision numbers. Use this before retrying after STALE_STATE.',inputSchema:{type:'object',properties:{limit:{type:'number',minimum:1,maximum:20}},additionalProperties:false},execute:(input)=>{const{limit=8}=input as{limit?:number};recordAgentActivity('Agent inspected recent changes');return ok(getPresenceState().activities.slice(-limit).reverse())}})
 register({name:'compare_breakpoints',description:'Compare semantic responsive properties across two breakpoints.',inputSchema:{type:'object',properties:{from:bp,to:bp},required:['from','to'],additionalProperties:false},execute:(input)=>{const{from,to}=input as{from:Breakpoint;to:Breakpoint};recordAgentActivity(`Agent compared ${from} and ${to}`);const s=getPresenceState();return ok(Object.values(s.project.nodes).map(n=>({id:n.id,name:n.name,from:n.responsive[from]??{},to:n.responsive[to]??{}})))}})

 const proposal=(name:string,description:string)=>register({name,description,inputSchema:{type:'object',properties:{breakpoint:bp,componentId:{type:'string'},changes:{type:'object',properties:{display:{type:'string',enum:['block','flex','grid','none']},direction:{type:'string',enum:['row','column']},gridColumns:{type:'number',minimum:1,maximum:4},gap:{type:'number',minimum:0,maximum:120},padding:{type:'number',minimum:0,maximum:120},width:{type:'string',enum:['auto','full']},align:{type:'string',enum:['start','center','end','stretch']},textAlign:{type:'string',enum:['left','center','right']},fontSize:{type:'number',minimum:1},lineHeight:{type:'number',minimum:.5,maximum:3},order:{type:'number'},visible:{type:'boolean'},imageRatio:{type:'string',enum:['16:9','4:3','1:1']}},additionalProperties:false},expectedRevision:{type:'number',minimum:1}},required:['breakpoint','componentId','changes','expectedRevision'],additionalProperties:false},execute:(input)=>{const{breakpoint,componentId,changes,expectedRevision}=input as{breakpoint:Breakpoint;componentId:string;changes:ResponsiveProps;expectedRevision:number};const s=getPresenceState();const admission=s.admissions.at(-1);const result=s.mutate({actorId:'agent',actorType:'agent',admissionId:admission?.id,label:`Agent proposed ${s.project.nodes[componentId]?.name??componentId} · ${breakpoint}`,change:{componentId,breakpoint,patch:changes},expectedRevision,provisional:true,explanation:'Adapted this surface while preserving the shared responsive goal.'});return ok(result)}})
 proposal('propose_layout_change','Propose a semantic layout change on the admitted agent’s assigned breakpoint. Requires active admission and current expectedRevision.')
 proposal('propose_component_change','Propose structured responsive component changes on the admitted agent’s assigned breakpoint. Changes stay provisional until human review.')
 proposal('propose_responsive_rule','Propose a breakpoint-specific responsive rule using structured product semantics. Requires active admission and current expectedRevision.')

 register({name:'submit_proposal',description:'Mark the admitted agent’s active Tablet proposal ready for human review.',inputSchema:{type:'object',properties:{proposalId:{type:'string'}},required:['proposalId'],additionalProperties:false},execute:(input)=>{const{proposalId}=input as{proposalId:string};const s=getPresenceState();const p=s.proposals.find(x=>x.id===proposalId);if(!p)return ok({ok:false,error:'NOT_FOUND'});const admission=s.admissions.at(-1);if(!admission||admission.status!=='admitted')return ok({ok:false,error:admission?.status==='paused'?'ADMISSION_PAUSED':admission?.status==='revoked'?'ADMISSION_REVOKED':admission?.status==='pending_user_approval'?'ADMISSION_PENDING':'ADMISSION_REQUIRED'});if(p.admissionId!==admission.id)return ok({ok:false,error:'CAPABILITY_NOT_GRANTED',message:'Proposal does not belong to the active admission.'});s.setProposalStatus(proposalId,'ready');recordAgentActivity(`Agent submitted ${p.operations.length} Tablet changes for review`,'proposal');return ok({ok:true,revision:s.canonicalRevision,proposalId})}})
 register({name:'explain_proposal',description:'Return the concise product-level rationale attached to an agent proposal.',inputSchema:{type:'object',properties:{proposalId:{type:'string'}},required:['proposalId'],additionalProperties:false},execute:(input)=>{const{proposalId}=input as{proposalId:string};const p=getPresenceState().proposals.find(x=>x.id===proposalId);return ok(p?{proposalId,explanation:p.explanation,status:p.status}:{error:'NOT_FOUND'})}})
 register({name:'release_role',description:'Release the browser agent’s current collaborator role and leave the workspace immediately.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:()=>{const s=getPresenceState();const a=s.admissions.at(-1);return ok(a?s.revokeAdmission(a.id):{ok:false,error:'ADMISSION_REQUIRED'})}})

 store.setWebMcp('connected')
 return true
}
